const items = [
  {
    lectureName: "Lecture Name 1",
    isLive: true,
    isVideo: true,
    handRaised: 23,
    image: "https://via.placeholder.com/300x200?text=Lecture+1",
    location: "Pathshala Pune",
    count: 279,
  },
  {
    lectureName: "Lecture Name 2",
    isLive: false,
    isVideo: true,
    handRaised: 5,
    image: "https://via.placeholder.com/300x200?text=Lecture+2",
    location: "Pathshala Mumbai",
    count: 64,
  },
  {
    lectureName: "Lecture Name 3",
    isLive: true,
    isVideo: false,
    handRaised: 10,
    image: "https://via.placeholder.com/300x200?text=Lecture+3",
    location: "Pathshala Delhi",
    count: 944,
  },
  {
    lectureName: "Lecture Name 4",
    isLive: false,
    isVideo: true,
    handRaised: 12,
    image: "https://via.placeholder.com/300x200?text=Lecture+4",
    location: "Pathshala Bangalore",
    count: 389,
  },
  {
    lectureName: "Lecture Name 5",
    isLive: true,
    isVideo: true,
    handRaised: 7,
    image: "https://via.placeholder.com/300x200?text=Lecture+5",
    location: "Pathshala Chennai",
    count: 157,
  },
  {
    lectureName: "Lecture Name 6",
    isLive: false,
    isVideo: true,
    handRaised: 15,
    image: "https://via.placeholder.com/300x200?text=Lecture+6",
    location: "Pathshala Hyderabad",
    count: 421,
  },
  {
    lectureName: "Lecture Name 7",
    isLive: true,
    isVideo: false,
    handRaised: 9,
    image: "https://via.placeholder.com/300x200?text=Lecture+7",
    location: "Pathshala Kolkata",
    count: 230,
  },
  {
    lectureName: "Lecture Name 8",
    isLive: true,
    isVideo: true,
    handRaised: 8,
    image: "https://via.placeholder.com/300x200?text=Lecture+8",
    location: "Pathshala Ahmedabad",
    count: 563,
  },
  {
    lectureName: "Lecture Name 9",
    isLive: false,
    isVideo: true,
    handRaised: 13,
    image: "https://via.placeholder.com/300x200?text=Lecture+9",
    location: "Pathshala Jaipur",
    count: 298,
  },
];

export default items;
